#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

_check() {
    if [[ $? -ne 0 ]]; then
        echo "Error processing: $1"
        exit 1
    fi
}

_do_build() {
    if [[ ! -d "build" ]]; then
        mkdir ${SCRIPT_DIR}/build
    fi
    cd ${SCRIPT_DIR}/build || _check "cd to build"
    echo "Building ..."
    cmake ..
    _check "cmake"
    make -j8
    _check "make"
    cd - || _check "cd back"
}

_clean() {
    cd ${SCRIPT_DIR} || _check "cd to root"
    rm -rf \
        build \
        mck/lib \

    cd - || _check "cd back"
}

_demo() {
    echo "Nothing to demo yet"
}

if [[ "$#" = "0" ]]; then
    # With no parameter: build
    _do_build
elif [[ "$1" = "clean" ]]; then
    _clean
    echo "Done."
elif [[ "$1" = "test" ]]; then
    _do_build
    shift
    echo "Testing... "
    for test in "${SCRIPT_DIR}"/build/test/bin/unit_*
    do
        $test "$@"
        _check "$test"
    done
elif [[ "$1" = "benchmark" ]]; then
    _do_build
    shift
    echo "Testing... "
    for test in "${SCRIPT_DIR}"/build/test/bin/benchmark_*
    do
        $test "$@"
        _check "$test"
    done
elif [[ "$1" = "ctest" ]]; then
    shift
    _do_build
    cd ${SCRIPT_DIR}/build || _check "cd to build"
    ctest "$@"
    _check "ctest"
    cd - || _check "cd back"
elif [[ "$1" = "demo" ]]; then
    _do_build
    _demo
elif [[ "$1" = "check" ]]; then
    _do_build
    cd ${SCRIPT_DIR}/build || _check "cd to build"
    make brasa_cppcheck
elif [[ "$1" = "install" ]]; then
    _do_build
    cd ${SCRIPT_DIR}/build || _check "cd to build"
    make DESTDIR="${SCRIPT_DIR}/install" install
elif [[ "$1" = "dependency" ]]; then
    dependency ${SCRIPT_DIR} ${SCRIPT_DIR}/src  \
        -o "-I ${SCRIPT_DIR}/src -std=c++20"    \
        -c ${SCRIPT_DIR}/src/                   \
        -A                                      \
        > depend.dot
    _check "dependency"
    dot -Tsvg -o depend.svg depend.dot
    _check "dot dependency"

else
    echo "Usage: `basename $0` [test|ctest|benchmark|clean|demo|check|install|dependency]"
fi
