version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2023.08
    steps:
      - checkout
      - run:
          name: Install tools
          command: sudo apt update && sudo apt install -y g++ cmake libboost-all-dev cppcheck
      - run:
          name: Build system
          command: ./runbuild
      - run:
          name: Test system
          command: ./runbuild test
      - run:
          name: Benchmarks
          command: ./runbuild benchmark
